<?xml version= "1.0" encoding= "UTF-8" standalone= "yes"?>
<!DOCTYPE Client [
<!ELEMENT Client(physio, phone_number,card_n, treatments_inprogress, prosthetics, exams, dob)>
	<!ATTLIST Client name CDATA #REQUIRED>
		<!ELEMENT physio (#PCDATA)>
		<!ELEMENT phone_number (#PCDATA)>
		<!ELEMENT card_n (#PCDATA)>
		<!ELEMENT treatments_inprogress (#PCDATA)>
		<!ELEMENT  prosthetics(#PCDATA)>
		<!ELEMENT exams (#PCDATA)>
		<!ELEMENT dob (#PCDATA)>
]>

<Client name = "Carlota!>
	<physio> 1 </physio>
	<phone_number> 6811087785</phone_number>
	<card_n> 123456788765 </card_n>
	<treatments_inprogress> 1 </treatments_inprogress>
	<prosthetics> 1 </prosthetics>
	<exams> 1 </exams>
	<dob> 2000/07/09 </dob>
</Client>
