<?xml version= "1.0" encoding= "UTF-8" standalone= "yes"?>

<!DOCTYPE Client [

<!ELEMENT Client (phone,card_n,email,doB, physio)>
	<!ATTLIST Client name CDATA #REQUIRED>
		<!ELEMENT phone (#PCDATA)>
		<!ELEMENT card_n (#PCDATA)>
		<!ELEMENT email (#PCDATA)>
		<!ELEMENT doB (#PCDATA)>
		<!ELEMENT physio (phone, doB, speciality, email)>
		<!ATTLIST physio name CDATA #REQUIRED>
			<!ELEMENT speciality (#PCDATA)>
]>


<Client name = "Carlota">
	<phone> 6811087785</phone>
	<card_n> 123456788765 </card_n>
	<email>carlota@gmail.com</email>
	<doB> 2000/07/09 </doB>
	<physio name= "Juanjo">
		<phone>6703167229</phone>
		<doB> 2000/08/08 </doB>
		<speciality>Trauma</speciality>
		<email>Juanjomartinez@gmail.com</email>
	</physio>
</Client>
